artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.zip

model_trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_transformation/train_scaled.csv
  test_path: artifacts/data_transformation/test_scaled.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_path: artifacts/data_transformation/test_scaled.csv
  elasticmodel: artifacts/model_trainer/ElasticNet_model.joblib
  ridgemodel: artifacts/model_trainer/Ridge_model.joblib
  lassomodel: artifacts/model_trainer/Lasso_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
